const sbiCustomerRequestForm = new URL("./sbi/customer_request_form.docx", import.meta.url).href;
const sbiInternetBankingRegistrationForm = new URL("./sbi/ib_registration_original.docx", import.meta.url).href;
const iciciCustomerDetailsUpdationForm = new URL("./icici/customer_details_updation.docx", import.meta.url).href;

export type LocalBankId = "sbi" | "icici";

export interface LocalFormTemplate {
  id: string;
  bank: LocalBankId;
  bankName: string;
  title: string;
  description: string;
  templateUrl: string;
  fileName: string;
  services: string[];
}

export const LOCAL_FORM_TEMPLATES: LocalFormTemplate[] = [
  {
    id: "sbi-customer-request",
    bank: "sbi",
    bankName: "SBI",
    title: "SBI Customer Request Form",
    description: "Local Word template with dynamic request-specific placeholders.",
    templateUrl: sbiCustomerRequestForm,
    fileName: "sbi_customer_request_form.docx",
    services: [
      "KYC Update",
      "Cheque Book Request",
      "Debit Card Request",
      "Mobile Number Update",
      "Address Update",
      "Nomination Update",
      "PAN Update",
      "Aadhaar Update",
      "CIF Transfer",
    ],
  },
  {
    id: "sbi-internet-banking-registration",
    bank: "sbi",
    bankName: "SBI",
    title: "SBI Internet Banking Registration",
    description: "Converted local DOCX template with boxed placeholders for customer details.",
    templateUrl: sbiInternetBankingRegistrationForm,
    fileName: "sbi_internet_banking_registration.docx",
    services: ["Internet Banking Registration"],
  },
  {
    id: "icici-customer-details-updation",
    bank: "icici",
    bankName: "ICICI",
    title: "ICICI Customer Details Updation Form",
    description: "Official customer details updation form loaded in the background.",
    templateUrl: iciciCustomerDetailsUpdationForm,
    fileName: "icici_customer_details_updation.docx",
    services: ["Customer Details Updation Form"],
  },
];

export const REQUEST_FIELD_MAP: Record<string, string[]> = {
  "KYC Update": [
    "applicant1_name",
    "applicant2_name",
    "account_number",
    "mobile_number",
    "email_id",
    "pan_number",
    "kyc_document_number",
    "issue_date",
    "valid_till_date",
    "place_of_issue",
    "signature",
    "passport_photo",
  ],
  "Cheque Book Request": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "email_id",
    "cheque_name",
    "number_of_leaflets",
    "correspondence_address_line1",
    "correspondence_address_line2",
    "correspondence_address_line3",
    "signature",
  ],
  "Debit Card Request": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "email_id",
    "correspondence_address_line1",
    "correspondence_address_line2",
    "correspondence_address_line3",
    "signature",
  ],
  "Mobile Number Update": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "new_mobile_number",
    "email_id",
    "signature",
  ],
  "Address Update": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "email_id",
    "correspondence_address_line1",
    "correspondence_address_line2",
    "correspondence_address_line3",
    "permanent_address_line1",
    "permanent_address_line2",
    "permanent_address_line3",
    "signature",
  ],
  "Nomination Update": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "email_id",
    "nominee_name",
    "nominee_relation",
    "nominee_address",
    "signature",
  ],
  "PAN Update": ["applicant1_name", "account_number", "mobile_number", "pan_number", "signature"],
  "Aadhaar Update": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "aadhaar_number_update",
    "aadhaar_number_delete",
    "signature",
  ],
  "CIF Transfer": [
    "applicant1_name",
    "account_number",
    "mobile_number",
    "transfer_branch_code",
    "transfer_cif_to_branch_name",
    "branch_name",
    "signature",
  ],
  "Internet Banking Registration": [
    "customer_name_boxes",
    "account_number_1_boxes",
    "account_1_single_joint",
    "account_1_transaction_rights",
    "account_1_limited_transaction_rights",
    "account_number_2_boxes",
    "account_2_single_joint",
    "account_2_transaction_rights",
    "account_2_limited_transaction_rights",
    "account_number_3_boxes",
    "account_3_single_joint",
    "account_3_transaction_rights",
    "account_3_limited_transaction_rights",
    "account_number_4_boxes",
    "account_4_single_joint",
    "account_4_transaction_rights",
    "account_4_limited_transaction_rights",
    "account_number_5_boxes",
    "account_5_single_joint",
    "account_5_transaction_rights",
    "account_5_limited_transaction_rights",
    "account_number_6_boxes",
    "account_6_single_joint",
    "account_6_transaction_rights",
    "account_6_limited_transaction_rights",
    "account_number_7_boxes",
    "account_7_single_joint",
    "account_7_transaction_rights",
    "account_7_limited_transaction_rights",
    "dob_dd_boxes",
    "dob_mm_boxes",
    "dob_yy_boxes",
    "mobile_number_boxes",
    "email_id",
    "submission_date",
    "customer_signature",
  ],
  "Customer Details Updation Form": [
    "branch_name",
    "request_date",
    "primary_holder_name",
    "account_number_boxes",
    "primary_mobile_number_boxes",
    "primary_pan_boxes",
    "primary_gender",
    "primary_occupation",
    "primary_marital_status",
    "primary_category",
    "primary_nationality",
    "primary_gross_annual_income",
    "house_building_name",
    "street_name",
    "locality",
    "city",
    "state",
    "country",
    "pin_code_boxes",
    "primary_holder_photo",
    "primary_signature",
  ],
};
