/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BanksBankIdRouteImport } from './routes/banks.$bankId'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksBankIdRoute = BanksBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => BanksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/banks/$bankId': typeof BanksBankIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/banks/$bankId': typeof BanksBankIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/banks/$bankId': typeof BanksBankIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/banks' | '/dashboard' | '/favorites' | '/banks/$bankId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banks' | '/dashboard' | '/favorites' | '/banks/$bankId'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/dashboard'
    | '/favorites'
    | '/banks/$bankId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/$bankId': {
      id: '/banks/$bankId'
      path: '/$bankId'
      fullPath: '/banks/$bankId'
      preLoaderRoute: typeof BanksBankIdRouteImport
      parentRoute: typeof BanksRoute
    }
  }
}

interface BanksRouteChildren {
  BanksBankIdRoute: typeof BanksBankIdRoute
}

const BanksRouteChildren: BanksRouteChildren = {
  BanksBankIdRoute: BanksBankIdRoute,
}

const BanksRouteWithChildren = BanksRoute._addFileChildren(BanksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
