/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PremiumSafetyShieldRouteImport } from './routes/premium/safety-shield'
import { Route as PremiumLetterGeneratorRouteImport } from './routes/premium/letter-generator'
import { Route as PremiumFormStudioRouteImport } from './routes/premium/form-studio'
import { Route as PremiumEmiPlannerRouteImport } from './routes/premium/emi-planner'
import { Route as BanksBankIdRouteImport } from './routes/banks.$bankId'
import { Route as BankIfscRouteImport } from './routes/bank.$ifsc'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSafetyShieldRoute = PremiumSafetyShieldRouteImport.update({
  id: '/premium/safety-shield',
  path: '/premium/safety-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumLetterGeneratorRoute = PremiumLetterGeneratorRouteImport.update({
  id: '/premium/letter-generator',
  path: '/premium/letter-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumFormStudioRoute = PremiumFormStudioRouteImport.update({
  id: '/premium/form-studio',
  path: '/premium/form-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumEmiPlannerRoute = PremiumEmiPlannerRouteImport.update({
  id: '/premium/emi-planner',
  path: '/premium/emi-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksBankIdRoute = BanksBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => BanksRoute,
} as any)
const BankIfscRoute = BankIfscRouteImport.update({
  id: '/bank/$ifsc',
  path: '/bank/$ifsc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/bank/$ifsc': typeof BankIfscRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/premium/emi-planner': typeof PremiumEmiPlannerRoute
  '/premium/form-studio': typeof PremiumFormStudioRoute
  '/premium/letter-generator': typeof PremiumLetterGeneratorRoute
  '/premium/safety-shield': typeof PremiumSafetyShieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/bank/$ifsc': typeof BankIfscRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/premium/emi-planner': typeof PremiumEmiPlannerRoute
  '/premium/form-studio': typeof PremiumFormStudioRoute
  '/premium/letter-generator': typeof PremiumLetterGeneratorRoute
  '/premium/safety-shield': typeof PremiumSafetyShieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/bank/$ifsc': typeof BankIfscRoute
  '/banks/$bankId': typeof BanksBankIdRoute
  '/premium/emi-planner': typeof PremiumEmiPlannerRoute
  '/premium/form-studio': typeof PremiumFormStudioRoute
  '/premium/letter-generator': typeof PremiumLetterGeneratorRoute
  '/premium/safety-shield': typeof PremiumSafetyShieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banks'
    | '/dashboard'
    | '/favorites'
    | '/bank/$ifsc'
    | '/banks/$bankId'
    | '/premium/emi-planner'
    | '/premium/form-studio'
    | '/premium/letter-generator'
    | '/premium/safety-shield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banks'
    | '/dashboard'
    | '/favorites'
    | '/bank/$ifsc'
    | '/banks/$bankId'
    | '/premium/emi-planner'
    | '/premium/form-studio'
    | '/premium/letter-generator'
    | '/premium/safety-shield'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/dashboard'
    | '/favorites'
    | '/bank/$ifsc'
    | '/banks/$bankId'
    | '/premium/emi-planner'
    | '/premium/form-studio'
    | '/premium/letter-generator'
    | '/premium/safety-shield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  BankIfscRoute: typeof BankIfscRoute
  PremiumEmiPlannerRoute: typeof PremiumEmiPlannerRoute
  PremiumFormStudioRoute: typeof PremiumFormStudioRoute
  PremiumLetterGeneratorRoute: typeof PremiumLetterGeneratorRoute
  PremiumSafetyShieldRoute: typeof PremiumSafetyShieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/safety-shield': {
      id: '/premium/safety-shield'
      path: '/premium/safety-shield'
      fullPath: '/premium/safety-shield'
      preLoaderRoute: typeof PremiumSafetyShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/letter-generator': {
      id: '/premium/letter-generator'
      path: '/premium/letter-generator'
      fullPath: '/premium/letter-generator'
      preLoaderRoute: typeof PremiumLetterGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/form-studio': {
      id: '/premium/form-studio'
      path: '/premium/form-studio'
      fullPath: '/premium/form-studio'
      preLoaderRoute: typeof PremiumFormStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/emi-planner': {
      id: '/premium/emi-planner'
      path: '/premium/emi-planner'
      fullPath: '/premium/emi-planner'
      preLoaderRoute: typeof PremiumEmiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks/$bankId': {
      id: '/banks/$bankId'
      path: '/$bankId'
      fullPath: '/banks/$bankId'
      preLoaderRoute: typeof BanksBankIdRouteImport
      parentRoute: typeof BanksRoute
    }
    '/bank/$ifsc': {
      id: '/bank/$ifsc'
      path: '/bank/$ifsc'
      fullPath: '/bank/$ifsc'
      preLoaderRoute: typeof BankIfscRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BanksRouteChildren {
  BanksBankIdRoute: typeof BanksBankIdRoute
}

const BanksRouteChildren: BanksRouteChildren = {
  BanksBankIdRoute: BanksBankIdRoute,
}

const BanksRouteWithChildren = BanksRoute._addFileChildren(BanksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  BankIfscRoute: BankIfscRoute,
  PremiumEmiPlannerRoute: PremiumEmiPlannerRoute,
  PremiumFormStudioRoute: PremiumFormStudioRoute,
  PremiumLetterGeneratorRoute: PremiumLetterGeneratorRoute,
  PremiumSafetyShieldRoute: PremiumSafetyShieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
